######
# Compose fragment file for the HoloROS driver
######

services:
  foxglove-studio:
    image: registry.gitlab.sitcore.net/xr-autonomy/holo-ros/foxglove-studio:${TAG:-latest}
    build:
      context: ./
      args: 
        TAG: ${TAG:-latest}
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    # env_file:
    # - ./.env
    # - path: ../.env
    #   required: false
    # volumes:
    # - ./foxglove-layout.json:/foxglove/default-layout.json
    network_mode: host
    ports:
    - "8080:8080"
