######
# Compose fragment file for the HoloROS driver
######
include:
  - "../networks.yaml"
  
services:
  foxglove-studio:
    image: ${REG:-registry.gitlab.sitcore.net/xr-autonomy}/champ/foxglove-studio:${TAG:-latest}
    build:
      context: ./
      args:
        TAG: ${TAG:-latest}
      platforms:
        - linux/amd64
        - linux/arm64
      cache_from:
        - ${REG:-registry.gitlab.sitcore.net/xr-autonomy}/champ/foxglove-studio:buildcache
      cache_to:
        - type=registry,ref=${REG:-registry.gitlab.sitcore.net/xr-autonomy}/champ/foxglove-studio:buildcache,mode=max
    networks:
      - ros2
    # volumes:
    # - ./foxglove-layout.json:/foxglove/default-layout.json
    profiles:
      - studio
    ports:
    - "8080:8080"
