######
# Compose fragment file for the HoloROS driver
######
include:
  - "../networks.yaml"
  
services:
  foxglove-studio:
    image: registry.gitlab.sitcore.net/xr-autonomy/champ/foxglove-studio${TAG:+:$TAG}
    build:
      context: ./
      args: 
        TAG: ${TAG:-latest}
      platforms:
        - linux/amd64
        - linux/arm64
      cache_from:
        - registry.gitlab.sitcore.net/xr-autonomy/champ/foxglove-studio:cache-amd64
        - registry.gitlab.sitcore.net/xr-autonomy/champ/foxglove-studio:cache-arm64
    networks:
      - ros2
    # volumes:
    # - ./foxglove-layout.json:/foxglove/default-layout.json
    profiles:
      - studio
    ports:
    - "8080:8080"
